# Generated by Django 3.0.4 on 2020-11-10 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Text')),
                ('commented_at', models.DateField(auto_now_add=True, verbose_name='Commented at')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('comment_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tour.TourComment', verbose_name='Comment')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_comment', to='tour.Tour', verbose_name='Tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_comment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
