# Generated by Django 3.0.4 on 2020-10-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='type',
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('Hiking', 'Hiking'), ('Sightseeing Tours', 'Sightseeing Tours')], default=1, max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('RUB', 'RUB')], default='AZN', max_length=31),
        ),
    ]
