# Generated by Django 3.0.4 on 2020-11-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tourcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourcomment',
            old_name='training',
            new_name='tour',
        ),
    ]
