# Generated by Django 3.0.4 on 2020-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_tourdetailaz_tourdetailen_tourdetailru_tourimage_tourschedule_toururl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='viewcount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
