# Generated by Django 3.0.4 on 2021-07-27 07:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210726_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='text_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
