# Generated by Django 3.0.4 on 2020-10-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20201017_0753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='adress',
            new_name='address',
        ),
    ]
