# Generated by Django 3.0.4 on 2021-08-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20210727_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourDetail',
        ),
    ]
