# Generated by Django 3.0.4 on 2020-11-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20201110_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
    ]
