# Generated by Django 3.0.4 on 2020-12-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tour_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='Activated'),
        ),
    ]
