# Generated by Django 3.0.4 on 2021-01-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourschedule',
            old_name='image',
            new_name='schedule_image',
        ),
    ]
