# Generated by Django 3.0.4 on 2021-01-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_auto_20210102_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourdetailaz',
            old_name='text',
            new_name='text_az',
        ),
        migrations.RenameField(
            model_name='tourdetailaz',
            old_name='title',
            new_name='title_az',
        ),
        migrations.RenameField(
            model_name='tourdetailen',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='tourdetailen',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='tourdetailru',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='tourdetailru',
            old_name='title',
            new_name='title_ru',
        ),
    ]
