# Generated by Django 3.0.4 on 2021-01-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20210102_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetailen',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetailen',
            name='title_en',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
