# Generated by Django 3.0.4 on 2020-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20200621_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='type',
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='tour', to='tour.Type', verbose_name='type'),
        ),
    ]
