# Generated by Django 3.0.4 on 2020-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_auto_20200627_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tour', to='tour.Type', verbose_name='type'),
        ),
    ]
