# Generated by Django 3.0.4 on 2021-01-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_auto_20210114_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDeny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Text')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Commented at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Commented at')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deny', to='tour.Tour')),
            ],
            options={
                'verbose_name': 'TourDeny',
                'verbose_name_plural': 'TourDenys',
            },
        ),
    ]
