# Generated by Django 3.0.4 on 2021-01-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_tourdeny'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourdeny',
            options={'verbose_name': 'TourDeny', 'verbose_name_plural': 'TourDenies'},
        ),
    ]
