# Generated by Django 3.0.4 on 2021-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_auto_20210217_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetailaz',
            name='text_az_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourdetailaz',
            name='text_az_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourdetailaz',
            name='text_az_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourdetailaz',
            name='title_az_az',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='tourdetailaz',
            name='title_az_en',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='tourdetailaz',
            name='title_az_ru',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
