# Generated by Django 3.0.4 on 2021-03-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_auto_20210309_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('title_az', models.CharField(max_length=31, null=True)),
                ('title_en', models.CharField(max_length=31, null=True)),
                ('title_ru', models.CharField(max_length=31, null=True)),
                ('text', models.TextField()),
                ('text_az', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_detail', to='tour.Tour')),
            ],
        ),
        migrations.RemoveField(
            model_name='tourdetailen',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='tourdetailru',
            name='tour',
        ),
        migrations.DeleteModel(
            name='TourDetailAZ',
        ),
        migrations.DeleteModel(
            name='TourDetailEN',
        ),
        migrations.DeleteModel(
            name='TourDetailRU',
        ),
    ]
