# Generated by Django 3.0.4 on 2021-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_auto_20210309_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='descriptionaz',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='descriptionen',
            new_name='description_az',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='descriptionru',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='tour',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
