# Generated by Django 3.0.4 on 2020-10-09 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=127, unique=True)),
                ('descriptionaz', models.TextField(blank=True, null=True)),
                ('descriptionen', models.TextField(blank=True, null=True)),
                ('descriptionru', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=127, null=True)),
                ('instagram', models.URLField(blank=True, max_length=127, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=31, null=True)),
                ('number2', models.CharField(blank=True, max_length=31, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='organizer/cover/')),
                ('viewcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_url', to='organizer.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizer/image/')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_image', to='organizer.Organizer')),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='organizer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer', to='organizer.OrganizerType'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
