# Generated by Django 3.0.4 on 2020-11-10 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('organizer_name', models.CharField(max_length=127, unique=True)),
                ('descriptionaz', models.TextField(blank=True, null=True)),
                ('descriptionen', models.TextField(blank=True, null=True)),
                ('descriptionru', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=127, null=True)),
                ('instagram', models.URLField(blank=True, max_length=127, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number_1', models.CharField(blank=True, max_length=31, null=True)),
                ('contact_number_2', models.CharField(blank=True, max_length=31, null=True)),
                ('profile_photo', models.ImageField(upload_to=None, verbose_name='organizer/profile-photo')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='organizer/cover/')),
                ('viewcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_url', to='organizer.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizer/image/')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_image', to='organizer.Organizer')),
            ],
        ),
        migrations.AddField(
            model_name='organizer',
            name='organizer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizer', to='organizer.OrganizerType'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('experience', models.CharField(choices=[('1 year', '1 Year'), ('2 year', '2 Year'), ('3 year', '3 Year'), ('4 year', '4 Year'), ('5+ year', '5+ Year')], max_length=50, verbose_name='Experience')),
                ('certification', models.CharField(max_length=50, verbose_name='Certification')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='organizer.Organizer', verbose_name='Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('experience', models.CharField(choices=[('1 year', '1 Year'), ('2 year', '2 Year'), ('3 year', '3 Year'), ('4 year', '4 Year'), ('5+ year', '5+ Year')], max_length=50, verbose_name='Experience')),
                ('certification', models.CharField(max_length=50, verbose_name='Certification')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='organizer.Organizer', verbose_name='Organizer')),
            ],
        ),
    ]
