# Generated by Django 3.0.4 on 2021-07-27 08:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
