# Generated by Django 3.0.4 on 2020-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='is_test',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
