# Generated by Django 3.0.4 on 2020-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='contact_number',
            new_name='contact_number_1',
        ),
        migrations.RenameField(
            model_name='organizer',
            old_name='number2',
            new_name='contact_number_2',
        ),
        migrations.AddField(
            model_name='organizer',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to=None, verbose_name='organizer/profile-photo'),
            preserve_default=False,
        ),
    ]
