# Generated by Django 3.0.4 on 2020-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20201115_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='profile_photo',
            field=models.ImageField(upload_to='organizer/cover/'),
        ),
    ]
