# Generated by Django 3.0.4 on 2021-02-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20201115_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='descriptionaz',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='descriptionen',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='descriptionru',
        ),
    ]
