# Generated by Django 3.0.4 on 2021-04-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='slide-images', verbose_name='Slide Image')),
            ],
            options={
                'verbose_name': 'HomeSlide',
                'verbose_name_plural': 'HomeSlides',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Partner Link')),
                ('partner_logo', models.ImageField(upload_to='partner-images', verbose_name='Partner Logo')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('instagram_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram Link')),
                ('facebook_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook Link')),
                ('linkedin_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='LinkedIn Link')),
            ],
            options={
                'verbose_name': 'SocialLink',
                'verbose_name_plural': 'SocialLinks',
            },
        ),
    ]
