# Generated by Django 3.0.4 on 2021-05-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='title',
        ),
    ]
