# Generated by Django 3.0.4 on 2020-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('link', models.URLField(max_length=300, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'SocialLink',
                'verbose_name_plural': 'SocialLinks',
            },
        ),
    ]
