# Generated by Django 3.0.4 on 2021-04-24 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0001_initial'),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_az', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='Azerbaijan', max_length=31)),
                ('city', models.CharField(blank=True, max_length=31, null=True)),
                ('address', models.CharField(blank=True, max_length=63, null=True)),
                ('price', models.IntegerField()),
                ('pricefor', models.IntegerField(default=1)),
                ('currency', models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('RUB', 'RUB')], default='AZN', max_length=31)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=31, null=True)),
                ('durationday', models.IntegerField(blank=True, null=True)),
                ('durationnight', models.IntegerField(blank=True, null=True)),
                ('datefrom', models.DateField(blank=True, null=True)),
                ('dateto', models.DateField(blank=True, null=True)),
                ('viewcount', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='activity/avatar/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='activity/cover/')),
                ('guide', models.CharField(blank=True, max_length=31, null=True)),
                ('availabledays', models.CharField(blank=True, max_length=31, null=True)),
                ('status', models.IntegerField(choices=[(1, 'publish'), (2, 'draft'), (3, 'past'), (4, 'deny')], default=1)),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating')),
                ('map_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Map Link')),
                ('activated', models.BooleanField(default=False, verbose_name='Activated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tour.TourType')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.Organizer')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_image', models.ImageField(upload_to='activity/schedule/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activity/image/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('title_az', models.CharField(max_length=31, null=True)),
                ('title_en', models.CharField(max_length=31, null=True)),
                ('title_ru', models.CharField(max_length=31, null=True)),
                ('text', models.TextField()),
                ('text_az', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_detail', to='activity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDeny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Text')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Commented at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Commented at')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deny', to='activity.Activity')),
            ],
            options={
                'verbose_name': 'ActivityDeny',
                'verbose_name_plural': 'ActivityDenies',
            },
        ),
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Text')),
                ('commented_at', models.DateField(auto_now_add=True, verbose_name='Commented at')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_comment', to='activity.Activity', verbose_name='Activity')),
                ('comment_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='activity.ActivityComment', verbose_name='Comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_comment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
