# Generated by Django 3.0.4 on 2020-11-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='map_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Map Link'),
        ),
    ]
