# Generated by Django 3.0.4 on 2020-10-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20201017_1114'),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tour.TourType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='currency',
            field=models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('RUB', 'RUB')], default='AZN', max_length=31),
        ),
    ]
