# Generated by Django 3.0.4 on 2021-01-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitydetailaz',
            old_name='text',
            new_name='text_az',
        ),
        migrations.RenameField(
            model_name='activitydetailaz',
            old_name='title',
            new_name='title_az',
        ),
        migrations.RenameField(
            model_name='activitydetailen',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='activitydetailen',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='activitydetailru',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='activitydetailru',
            old_name='title',
            new_name='title_ru',
        ),
    ]
