# Generated by Django 3.0.4 on 2020-06-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_auto_20200627_1253'),
        ('activity', '0004_auto_20200627_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='activity', to='tour.Type', verbose_name='type'),
        ),
    ]
