# Generated by Django 3.0.4 on 2021-01-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activity_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityschedule',
            old_name='image',
            new_name='schedule_image',
        ),
    ]
