# Generated by Django 3.0.4 on 2021-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20210103_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.IntegerField(choices=[(1, 'publish'), (2, 'draft'), (3, 'past'), (4, 'deny')], default=1),
        ),
    ]
