# Generated by Django 3.0.4 on 2021-03-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_activitydeny'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('title_az', models.CharField(max_length=31, null=True)),
                ('title_en', models.CharField(max_length=31, null=True)),
                ('title_ru', models.CharField(max_length=31, null=True)),
                ('text', models.TextField()),
                ('text_az', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activitydetailen',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitydetailru',
            name='activity',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='descriptionaz',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='descriptionen',
            new_name='description_az',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='descriptionru',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='activity',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ActivityDetailAZ',
        ),
        migrations.DeleteModel(
            name='ActivityDetailEN',
        ),
        migrations.DeleteModel(
            name='ActivityDetailRU',
        ),
        migrations.AddField(
            model_name='activitydetail',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_detail', to='activity.Activity'),
        ),
    ]
