# Generated by Django 3.0.4 on 2020-11-08 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('descriptionaz', models.TextField(blank=True, null=True)),
                ('descriptionen', models.TextField(blank=True, null=True)),
                ('descriptionru', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='Azerbaijan', max_length=31)),
                ('city', models.CharField(blank=True, max_length=31, null=True)),
                ('address', models.CharField(blank=True, max_length=63, null=True)),
                ('price', models.IntegerField()),
                ('pricefor', models.IntegerField(default=1)),
                ('currency', models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('RUB', 'RUB')], default='AZN', max_length=31)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=31, null=True)),
                ('durationday', models.IntegerField(blank=True, null=True)),
                ('durationnight', models.IntegerField(blank=True, null=True)),
                ('datefrom', models.DateField(blank=True, null=True)),
                ('dateto', models.DateField(blank=True, null=True)),
                ('viewcount', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='training/avatar/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='training/cover/')),
                ('trainer', models.CharField(blank=True, max_length=31, null=True)),
                ('availabledays', models.CharField(blank=True, max_length=31, null=True)),
                ('status', models.IntegerField(choices=[(1, 'publish'), (2, 'draft'), (3, 'past')], default=1)),
                ('start_hour', models.TimeField(verbose_name='Start Hour')),
                ('finish_hour', models.TimeField(verbose_name='Finish Hour')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training', to='organizer.Organizer')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='tour.TourType')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_url', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training/schedule/')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_schedule', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training/image/')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_image', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDetailRU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('text', models.TextField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_detail_ru', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDetailEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('text', models.TextField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_detail_en', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDetailAZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('text', models.TextField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_detail_az', to='training.Training')),
            ],
        ),
    ]
