# Generated by Django 3.0.4 on 2021-07-26 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0001_initial'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_az', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='Azerbaijan', max_length=31)),
                ('city', models.CharField(blank=True, max_length=31, null=True)),
                ('address', models.CharField(blank=True, max_length=63, null=True)),
                ('price', models.IntegerField()),
                ('pricefor', models.IntegerField(default=1)),
                ('currency', models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('RUB', 'RUB')], default='AZN', max_length=31)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, max_length=31, null=True)),
                ('durationday', models.IntegerField(blank=True, null=True)),
                ('durationnight', models.IntegerField(blank=True, null=True)),
                ('datefrom', models.DateField(blank=True, null=True)),
                ('dateto', models.DateField(blank=True, null=True)),
                ('viewcount', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='training/avatar/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='training/cover/')),
                ('trainer', models.CharField(blank=True, max_length=31, null=True)),
                ('availabledays', models.CharField(blank=True, max_length=31, null=True)),
                ('status', models.IntegerField(choices=[(1, 'publish'), (2, 'draft'), (3, 'past'), (4, 'deny')], default=1)),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rating')),
                ('start_hour', models.TimeField(verbose_name='Start Hour')),
                ('finish_hour', models.TimeField(verbose_name='Finish Hour')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('map_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Map Link')),
                ('activated', models.BooleanField(default=False, verbose_name='Activated')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training', to='organizer.Organizer')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='tour.TourType')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_url', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_image', models.ImageField(upload_to='training/schedule/')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_schedule', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training/image/')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_image', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('title_az', models.CharField(max_length=31, null=True)),
                ('title_en', models.CharField(max_length=31, null=True)),
                ('title_ru', models.CharField(max_length=31, null=True)),
                ('text', models.TextField()),
                ('text_az', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_detail', to='training.Training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDeny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Text')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Commented at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Commented at')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deny', to='training.Training')),
            ],
            options={
                'verbose_name': 'TrainingDeny',
                'verbose_name_plural': 'TrainingDenies',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Text')),
                ('commented_at', models.DateField(auto_now_add=True, verbose_name='Commented at')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('comment_reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='training.Comment', verbose_name='Comment')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='training.Training', verbose_name='Training')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
