# Generated by Django 3.0.4 on 2021-08-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20210727_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingDetail',
        ),
    ]
