# Generated by Django 3.0.4 on 2020-10-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20201017_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='currency',
            field=models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('RUB', 'RUB')], default='AZN', max_length=31),
        ),
    ]
