# Generated by Django 3.0.4 on 2021-01-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingdetailaz',
            old_name='text',
            new_name='text_az',
        ),
        migrations.RenameField(
            model_name='trainingdetailaz',
            old_name='title',
            new_name='title_az',
        ),
        migrations.RenameField(
            model_name='trainingdetailen',
            old_name='text',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='trainingdetailen',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='trainingdetailru',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='trainingdetailru',
            old_name='title',
            new_name='title_ru',
        ),
    ]
