# Generated by Django 3.0.4 on 2020-06-27 12:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20200621_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'beach'), (2, 'hiking'), (3, 'mountain'), (4, 'test'), (5, 'test1')], max_length=3, null=True),
        ),
    ]
